[package]
name = "error-trace"
version = "0.3.0"
edition = "2021"
authors = ["Trent Shailer"]
license = "MIT OR Apache-2.0"

[dependencies]
owo-colors = { version = "4.0.0", optional = true }

[features]
color = ["dep:owo-colors"]
