[package]
name = "error-trace"
version = "0.4.2"
edition = "2021"
authors = ["Trent Shailer"]
license = "MIT OR Apache-2.0"

[dependencies]
log = { version = "0.4.21", optional = true }
owo-colors = { version = "4.0.0", optional = true }

[features]
color = ["dep:owo-colors"]
log = ["dep:log"]
